### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by SmashITs** [pFarb/awesome-crypto-papers#4]
Dear pFarb,

1) Could you please add below the title "Online crypto challenges" a
link to MTC3: https://www.mysterytwisterc3.org/en/
Cipher contest with more
than 200 challenges of different levels, a moderated forum, and a
hall-of-fame.

2) I'd be happy if you could add a section about educational crypto
software. Here, you could add a link and a description to the set of
programs from the CrypTool project: CT1, CT2, JCT, and CTO.
See: https://en.wikipedia.org/wiki/CrypTool

Thanks.

**Comment by pFarb** [comment]
Hi @SmashITs! Thank you for your suggestions! CryptTool was already added, and I'm adding MTC3 now
