### ISSUE TITLE
Add this project to the https://github.com/sobolevn/awesome-cryptography

### ISSUE THREAD

**Issue by sobolevn** [pFarb/awesome-crypto-papers#6]
Hi, thanks for this project! Awesome list indeed.

Can you please add this repo to https://github.com/sobolevn/awesome-cryptography
I know, that I can do it myself, but I would like you invite you to do the honours! 👍 

Related: https://github.com/sobolevn/awesome-cryptography/issues/89

Cheers!

**Comment by pFarb** [comment]
Hi @sobolevn!

Sorry, I haven't looked here in a while. 

Looks like someone has already added this repo to your great awesome-cryptography repo! https://github.com/sobolevn/awesome-cryptography/pull/63.

So, we're already connected! 🙌

Thank you for your hard work, and have a great week!
