### ISSUE TITLE
[Recommendation] Add a new challenge website

### ISSUE THREAD

**Issue by dlesnoff** [pFarb/awesome-crypto-papers#9]
cryptohack https://cryptohack.org/ is a great CTF based on CryptoPal.

**Comment by cothan** [comment]
I totally agree that cryptohack is a great resource to learn crypto, I see my student and friend (`pcback` and `ndh`) participate in cryptohack.org, they are very good. 
Somehow, I think everyone who wants to learn crypto should start with cryptohack, they provide super useful related paper, resources to learn about Crypto along the way, hand-on experience. 

Just one thing though, I don't think Cryptohack is based on CryptoPal. It is itself, much greater than CryptoPal. 

Disclaimer: I am not affiliated with CryptoHack in any way, by any means.

**Comment by pFarb** [comment]
Thank you for suggestion! Cryptohack has quite extensive challenges indeed.
